"use client";
// ============================================================
// src/components/InvestigationReport.tsx
// The main report display — the heart of TruthLens
// Shows all investigation results in a "case file" style
// ============================================================

import { useState } from "react";
import {
  FileText, Fingerprint, CheckSquare, TrendingUp,
  TrendingDown, Search, ArrowRight, Save, Check,
  Globe, AlertCircle
} from "lucide-react";
import { type InvestigationReport as ReportType } from "@/types/investigation";
import { generateCaseId, getVerdictEmoji } from "@/lib/utils";
import { saveInvestigation } from "@/lib/storage";
import VerdictBadge from "./VerdictBadge";
import CredibilityMeter from "./CredibilityMeter";
import EvidenceCard from "./EvidenceCard";
import RedFlagsPanel from "./RedFlagsPanel";
import CopyButton from "./CopyButton";
import DownloadReportButton from "./DownloadReportButton";

interface InvestigationReportProps {
  report: ReportType;
  claim: string;
  isLiveSearch: boolean;
}

// Helper: section header with accent line
function SectionHeader({ icon: Icon, title, count }: {
  icon: React.ElementType;
  title: string;
  count?: number;
}) {
  return (
    <div className="flex items-center gap-2 mb-3">
      <Icon className="w-4 h-4 text-signal" />
      <h3 className="font-display font-bold text-sm text-bright uppercase tracking-wider">
        {title}
      </h3>
      {count !== undefined && (
        <span className="font-mono text-[10px] text-signal/60 bg-signal/10 border border-signal/20 px-1.5 py-0.5 rounded">
          {count}
        </span>
      )}
      <div className="flex-1 h-px bg-border/50 ml-2" />
    </div>
  );
}

export default function InvestigationReport({
  report,
  claim,
  isLiveSearch,
}: InvestigationReportProps) {
  const [caseId] = useState(() => generateCaseId());
  const [saved, setSaved] = useState(false);

  // Build the plain text version for copying
  const reportText = `
TRUTHLENS INVESTIGATION REPORT
Case ID: ${caseId}
Verdict: ${getVerdictEmoji(report.verdict)} ${report.verdict} (${report.credibilityScore}/100)

CLAIM: "${claim}"

SUMMARY: ${report.summary}

EXTRACTED CLAIMS:
${report.extractedClaims.map((c, i) => `${i + 1}. ${c}`).join("\n")}

SUPPORTING EVIDENCE:
${report.supportingEvidence.map((e, i) => `${i + 1}. [${e.sourceType}] ${e.point}`).join("\n")}

CONTRADICTING EVIDENCE:
${report.contradictingEvidence.map((e, i) => `${i + 1}. [${e.sourceType}] ${e.point}`).join("\n")}

RISK SIGNALS:
${report.redFlags.map((f) => `• ${f}`).join("\n")}

NEXT STEPS:
${report.nextSteps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

Generated by TruthLens — AI Credibility Investigation
`.trim();

  // Save the report to localStorage
  function handleSave() {
    saveInvestigation({
      id: caseId,
      claim,
      report,
      timestamp: Date.now(),
      isLiveSearch,
    });
    setSaved(true);
  }

  return (
    <div className="space-y-6">
      {/* ---- Case Header ---- */}
      <div className="glass rounded-xl border border-border p-5 corner-accent">
        {/* Case ID + Meta */}
        <div className="flex items-center justify-between flex-wrap gap-2 mb-4">
          <div className="flex items-center gap-3">
            <span className="font-mono text-xs text-signal bg-signal/10 border border-signal/30 px-2 py-1 rounded">
              CASE #{caseId}
            </span>
            {/* Live search indicator */}
            <span
              className={`flex items-center gap-1 font-mono text-[10px] px-2 py-1 rounded border ${
                isLiveSearch
                  ? "text-verify border-verify/30 bg-verify/10"
                  : "text-caution border-caution/30 bg-caution/10"
              }`}
            >
              <Globe className="w-3 h-3" />
              {isLiveSearch ? "Live Web Search" : "AI Knowledge Only"}
            </span>
          </div>

          {/* Action buttons */}
          <div className="flex items-center gap-2 flex-wrap">
            <button
              onClick={handleSave}
              disabled={saved}
              className={`flex items-center gap-2 px-3 py-1.5 rounded border text-xs font-mono font-medium transition-all ${
                saved
                  ? "border-verify/40 text-verify bg-verify/10"
                  : "border-border text-ghost hover:border-verify/30 hover:text-pale hover:bg-verify/5"
              }`}
            >
              {saved ? <Check className="w-3.5 h-3.5" /> : <Save className="w-3.5 h-3.5" />}
              {saved ? "Saved" : "Save Case"}
            </button>
            <CopyButton text={reportText} />
            <DownloadReportButton report={report} claim={claim} caseId={caseId} />
          </div>
        </div>

        {/* Case Title */}
        <h2 className="font-display font-black text-xl sm:text-2xl text-bright mb-1 leading-tight">
          {report.caseTitle}
        </h2>
        <p className="font-body text-sm text-ghost leading-relaxed mb-4">
          &ldquo;{claim}&rdquo;
        </p>

        {/* Verdict + Score side by side on larger screens */}
        <div className="grid sm:grid-cols-2 gap-4">
          {/* Verdict */}
          <div className="space-y-2">
            <span className="font-mono text-[10px] text-dim uppercase tracking-widest">Verdict</span>
            <VerdictBadge verdict={report.verdict} size="lg" />
          </div>

          {/* Divider */}
          <div className="hidden sm:block w-px bg-border self-stretch" />
        </div>
      </div>

      {/* ---- AI Disclaimer (if no live search) ---- */}
      {!isLiveSearch && (
        <div className="flex items-start gap-3 p-4 rounded-lg border border-caution/30 bg-caution/5">
          <AlertCircle className="w-4 h-4 text-caution shrink-0 mt-0.5" />
          <p className="text-xs text-caution/90 leading-relaxed">
            <strong>AI-Assisted Analysis:</strong> This report was generated from AI training knowledge,
            not live web search. Results may not reflect the most recent information.
            Always verify through primary sources.
          </p>
        </div>
      )}

      {/* ---- Credibility Meter ---- */}
      <div className="glass rounded-xl border border-border p-5">
        <CredibilityMeter
          score={report.credibilityScore}
          explanation={report.confidenceExplanation}
        />
      </div>

      {/* ---- Summary ---- */}
      <div className="glass rounded-xl border border-border p-5">
        <SectionHeader icon={FileText} title="Investigation Summary" />
        <p className="text-sm text-pale leading-relaxed">{report.summary}</p>
      </div>

      {/* ---- Extracted Claims ---- */}
      <div className="glass rounded-xl border border-border p-5">
        <SectionHeader icon={Fingerprint} title="Extracted Claims" count={report.extractedClaims.length} />
        <ul className="space-y-2">
          {report.extractedClaims.map((claim, i) => (
            <li key={i} className="flex items-start gap-3">
              <span className="font-mono text-[10px] text-signal/60 shrink-0 mt-1 bg-signal/10 px-1.5 py-0.5 rounded border border-signal/20">
                C{String(i + 1).padStart(2, "0")}
              </span>
              <p className="text-sm text-pale leading-relaxed">{claim}</p>
            </li>
          ))}
        </ul>
      </div>

      {/* ---- Evidence Sections ---- */}
      <div className="grid sm:grid-cols-2 gap-4">
        {/* Supporting Evidence */}
        <div className="glass rounded-xl border border-border p-5">
          <SectionHeader icon={TrendingUp} title="Supporting Evidence" count={report.supportingEvidence.length} />
          <div className="space-y-2">
            {report.supportingEvidence.map((evidence, i) => (
              <EvidenceCard key={i} evidence={evidence} type="supporting" index={i} />
            ))}
          </div>
        </div>

        {/* Contradicting Evidence */}
        <div className="glass rounded-xl border border-border p-5">
          <SectionHeader icon={TrendingDown} title="Contradicting Evidence" count={report.contradictingEvidence.length} />
          <div className="space-y-2">
            {report.contradictingEvidence.map((evidence, i) => (
              <EvidenceCard key={i} evidence={evidence} type="contradicting" index={i} />
            ))}
          </div>
        </div>
      </div>

      {/* ---- Red Flags + Missing Context ---- */}
      <div className="glass rounded-xl border border-border p-5">
        <SectionHeader icon={CheckSquare} title="Risk Analysis" />
        <RedFlagsPanel
          redFlags={report.redFlags}
          missingContext={report.missingContext}
        />
      </div>

      {/* ---- Suggested Searches ---- */}
      <div className="glass rounded-xl border border-border p-5">
        <SectionHeader icon={Search} title="Verify It Yourself" count={report.suggestedSearchQueries.length} />
        <p className="text-xs text-dim mb-3">
          Copy these queries into Google or your preferred search engine to verify manually:
        </p>
        <div className="space-y-2">
          {report.suggestedSearchQueries.map((query, i) => (
            <a
              key={i}
              href={`https://www.google.com/search?q=${encodeURIComponent(query)}`}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-3 p-2.5 rounded border border-border hover:border-signal/30 hover:bg-signal/5 transition-all group"
            >
              <span className="font-mono text-[10px] text-dim shrink-0">
                {String(i + 1).padStart(2, "0")}
              </span>
              <span className="text-xs text-ghost group-hover:text-pale flex-1 font-mono">
                {query}
              </span>
              <ArrowRight className="w-3 h-3 text-dim group-hover:text-signal transition-colors shrink-0" />
            </a>
          ))}
        </div>
      </div>

      {/* ---- Next Steps ---- */}
      <div className="glass rounded-xl border border-border p-5">
        <SectionHeader icon={ArrowRight} title="Recommended Next Steps" />
        <ol className="space-y-2">
          {report.nextSteps.map((step, i) => (
            <li key={i} className="flex items-start gap-3">
              <span className="font-mono text-xs text-signal font-bold shrink-0 mt-0.5">
                {String(i + 1).padStart(2, "0")}.
              </span>
              <p className="text-sm text-pale leading-relaxed">{step}</p>
            </li>
          ))}
        </ol>
      </div>
    </div>
  );
}
